#TODO: add_definitions(-DSPDLOG_WCHAR_FILENAMES)
#TODO: add_definitions(-DSPDLOG_WCHAR_TO_UTF8_SUPPORT)
find_package(spdlog CONFIG REQUIRED)
find_package(jsoncpp CONFIG REQUIRED)
find_package(mio CONFIG REQUIRED)
#TODO: set(WITH_WINDOWS_UTF8_FILENAMES TRUE)
find_package(rocksdb CONFIG REQUIRED)
find_package(civetweb CONFIG REQUIRED)
find_package(fmt CONFIG REQUIRED)
find_package(asio CONFIG REQUIRED)
find_package(Catch2 CONFIG REQUIRED)
find_package(ZLIB REQUIRED)
find_package(minizip CONFIG REQUIRED)
find_package(roaring CONFIG REQUIRED)